### ISSUE TITLE
Automate Employee Access to EC2 Instances

### ISSUE THREAD

**Issue by nikshepkulli-CTO** [starteryouInc/Starteryou-Website#18]
---

### **Ticket Title**: Automate Employee Access to EC2 Instances with Existing Key Pairs  

---

### **Description**:  
Streamline the process of giving employees access to newly created EC2 instances by automating the addition of user accounts and assigning existing key pairs to each user for SSH access.

---

#### **1. Use Existing Key Pairs for Employees**  
Ensure that each employee already has an SSH key pair, and the public keys are available for setup on new EC2 instances.

- **Steps**:  
  1. Collect all employees' public SSH keys.
  2. Store these keys in a secure location or configuration file for easy reference.

---

#### **2. Automate User Creation on EC2 Instances**  
Use the following script to automate the creation of user accounts and setup of their SSH access. This will ensure that all employees are automatically added to newly launched instances.

```bash
#!/bin/bash

# List of employee usernames and their corresponding public key file paths
declare -A EMPLOYEES
EMPLOYEES=(
  ["user1"]="/path/to/user1.pub"
  ["user2"]="/path/to/user2.pub"
  ["user3"]="/path/to/user3.pub"
)

for EMPLOYEE in "${!EMPLOYEES[@]}"; do
  # Create the user if not exists
  if id "$EMPLOYEE" &>/dev/null; then
    echo "User $EMPLOYEE already exists."
  else
    sudo adduser "$EMPLOYEE" --gecos "" --disabled-password
    echo "User $EMPLOYEE created."
  fi

  # Set up .ssh directory and add public key
  sudo mkdir -p /home/"$EMPLOYEE"/.ssh
  sudo chmod 700 /home/"$EMPLOYEE"/.ssh
  sudo cp "${EMPLOYEES[$EMPLOYEE]}" /home/"$EMPLOYEE"/.ssh/authorized_keys
  sudo chmod 600 /home/"$EMPLOYEE"/.ssh/authorized_keys
  sudo chown -R "$EMPLOYEE":"$EMPLOYEE" /home/"$EMPLOYEE"/.ssh
  
  echo "SSH access configured for $EMPLOYEE."
done
```

- Replace `user1`, `user2`, etc., with employee usernames.
- Replace `/path/to/userX.pub` with the paths to the public key files of employees.

---

### **3. Add Automation for New EC2 Instances**  
To automate the process for every new instance:
- Integrate the script above into the **EC2 instance launch template** or **user data** field. This will run the script as part of the instance initialization process.

#### Example:
1. Go to the **EC2 Dashboard** > **Launch Templates**.
2. Create or edit a launch template.
3. In the **Advanced Details** section, add the script under **User data**.

```bash
#!/bin/bash
# Add the script here to run on instance startup
```

---

### **Expected Outcome**:  
- All new EC2 instances will automatically have user accounts and SSH access configured for employees.  
- No need to manually add employees to instances.  
- Simplified and consistent process for managing employee access.  
- All the existing ec2 instances should have this automation.

---

**Comment by arpitshrivastva** [comment]
This task has been completed for all three servers and successfully validated. I am closing this ticket.
