### ISSUE TITLE
I encountered a bug after editing text the play card doesn't dynamically adjusts its size, or there is no text limit.

### ISSUE THREAD

**Issue by nikshepkulli-CTO** [starteryouInc/Starteryou-Website#42]

**Comment by MdAsifSid** [comment]
**Fix:**  
Implemented dynamic sizing for the card to adjust its dimensions based on the text content.  
This fix has been implemented in my recent [PR](https://github.com/starteryouInc/Starteryou-Website/pull/44#issue-2756328118).
