### ISSUE TITLE
Please delete the tech team section on about us at the bottom

### ISSUE THREAD

**Issue by Mblingo** [starteryouInc/Starteryou-Website#47]
We will just have all employees listed on meet the team section. Please also include option to edit the pictures of each member and link to include our Linkedins. 

![Image](https://github.com/user-attachments/assets/3eed49b6-be1f-46d2-a516-81943141d2c0)

**Comment by MdAsifSid** [comment]
I'll comment out the Tech Team section in the code so we can reuse it in the future if needed. LinkedIn options were not included in the Figma design, but I can create them if required
