### ISSUE TITLE
Play card doesn't format texts, new line or spaces.

### ISSUE THREAD

**Issue by nikshepkulli-CTO** [starteryouInc/Starteryou-Website#49]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/4480e46c-5a36-4e34-86e2-76ecbe32d932" />

**Comment by MdAsifSid** [comment]
Okay, I'll fix the issue with text formatting in the Play card.

@nikshepkulli-CTO  @Mblingo , I noticed you're adding a lot of content to the About Us page. I coded each component based on the Figma design, and adding excessive content might impact the layout and appearance. 
If you need to add more content, I'll have to restructure the frontend components to accommodate it properly.

It's a request to please add data according to the component design to maintain consistency and layout integrity.
